# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160320_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movableimage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='movableimage',
            name='uploaded_by_user',
        ),
        migrations.AlterUniqueTogether(
            name='movableimagerendition',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='movableimagerendition',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='movableimagerendition',
            name='image',
        ),
        migrations.DeleteModel(
            name='MovableImage',
        ),
        migrations.DeleteModel(
            name='MovableImageRendition',
        ),
    ]
